apiVersion: v1
kind: Service
metadata:
  name: {{ include "entregable4-chart.fullname" . }}
  labels:
    app: {{ include "entregable4-chart.name" . }}   # MUY IMPORTANTE
    release: monitoring                             # para Prometheus Operator
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http                                     # DEBE llamarse igual que en el ServiceMonitor
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "entregable4-chart.name" . }}    # tiene que coincidir EXACTO
