apiVersion: v1
kind: Service
metadata:
  name: {{ include "entregable4-chart.fullname" . }}
  labels:
    app: {{ include "entregable4-chart.name" . }}   # ðŸ”¥ NECESARIO para ServiceMonitor
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http                                    # ðŸ”¥ NECESARIO para ServiceMonitor
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "entregable4-chart.name" . }}
