apiVersion: v1
kind: Service
metadata:
  name: {{ include "entregable4-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ include "entregable4-chart.name" . }}
